// <auto-generated />
using System;
using GobernaRegistroBio.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GobernaRegistroBio.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211017041837_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GobernaRegistroBio.App.Dominio.Gobernacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Aforo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("gobernacio");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Gobernacion");
                });

            modelBuilder.Entity("GobernaRegistroBio.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ubicacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("GobernaRegistroBio.App.Dominio.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Autoriza_Ingreso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DependenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Fecha_Diagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tiempo_Aislamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("personaId")
                        .HasColumnType("int");

                    b.Property<int>("sintomas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DependenciaId");

                    b.HasIndex("personaId");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("GobernaRegistroBio.App.Dominio.Dependencia", b =>
                {
                    b.HasBaseType("GobernaRegistroBio.App.Dominio.Gobernacion");

                    b.Property<string>("Aforo_PorDependencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ubicacion")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Dependencia");
                });

            modelBuilder.Entity("GobernaRegistroBio.App.Dominio.Gobernador_Asesores", b =>
                {
                    b.HasBaseType("GobernaRegistroBio.App.Dominio.Persona");

                    b.Property<string>("Oficinas_Visitadas")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Gobernador_Asesores");
                });

            modelBuilder.Entity("GobernaRegistroBio.App.Dominio.Personal_Aseo", b =>
                {
                    b.HasBaseType("GobernaRegistroBio.App.Dominio.Persona");

                    b.Property<string>("Turno_Servicio")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Personal_Aseo");
                });

            modelBuilder.Entity("GobernaRegistroBio.App.Dominio.Proveedores_Servicios", b =>
                {
                    b.HasBaseType("GobernaRegistroBio.App.Dominio.Persona");

                    b.Property<string>("Servicio_Realizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidad_Servicio")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Proveedores_Servicios");
                });

            modelBuilder.Entity("GobernaRegistroBio.App.Dominio.Secretarios_Despacho", b =>
                {
                    b.HasBaseType("GobernaRegistroBio.App.Dominio.Persona");

                    b.Property<string>("Despacho")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Secretarios_Despacho");
                });

            modelBuilder.Entity("GobernaRegistroBio.App.Dominio.Registro", b =>
                {
                    b.HasOne("GobernaRegistroBio.App.Dominio.Dependencia", "Dependencia")
                        .WithMany()
                        .HasForeignKey("DependenciaId");

                    b.HasOne("GobernaRegistroBio.App.Dominio.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("personaId");

                    b.Navigation("Dependencia");

                    b.Navigation("persona");
                });
#pragma warning restore 612, 618
        }
    }
}
